---
- hosts: all
  become: true
  tasks:

  - name: install updates
    apt:
      update_cache: yes


- hosts: workstations
  become: true
  tasks:
 
  - name: install unzip
    package:
      name: unzip
 
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: test_servers
  become: true
  tasks:

  - name: install packages on test_servers
    apt: 
     name:
      - apache2
     state: latest


- hosts: dev_servers
  become: true
  tasks:
          
  - name: install packages on dev_servers
    apt:
     name:
      - apache2 
     state: latest

  - name: copy html file for site
    tags: apache,apache,apache2,httpd
    copy:
     src: default_site.html      
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644
