---
 
 - hosts: all
   become: true
   pre_tasks:
 
   - name: update repository index (CentOS)
     tags: always
     package:
       update_cache: yes
     changed_when: false
     

 


 - hosts: dev_servers
   become: true
   roles:
     - dev_servers
 
 - hosts: test_servers
   become: true
   roles:
     - test_servers
 
 - hosts: workstations
   become: true
   roles:
     - cleanDockerImages